version: 1.0.{build}

environment:
  BUILD_DIR: "build"
  NPCAP_USERNAME:
    secure: iVuVl18E7ZfsuRjz0YKJKQ==
  NPCAP_PASSWORD:
    secure: 8sWBrDudyutFv+4Eq6teJA==
  PYTHON: "C:\\Python38-x64"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      platform: "x86"
      generator: "Visual Studio 14 2015"
      arch: "Win32"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: "x86"
      generator: "Visual Studio 15 2017"
      arch: "Win32"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - cmd: ci\install_npcap.bat
  - cmd: python -m pip install --upgrade pip
  - cmd: python -m pip install -r requirements.txt
  - cmd: ci\install_tcpreplay.bat

build_script:
  - cmd: ci\find_ip.bat
  - cmd: cmake -G "%generator%" -A "%arch%" -DPCAP_ROOT="C:\Npcap-sdk" -DPCAPPP_TESTS_EXAMPLESTEST_ARGS="--interface;%NetworkIP%" -S . -B "%BUILD_DIR%"

test_script:
  - cmd: ctest -S "%BUILD_DIR%/testing.cmake" -C "Debug" --extra-verbose --output-on-failure
