name: PcapPlusPlus Build Examples with VCPKG

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install CMake
      run: sudo apt-get -y install cmake
      if: matrix.os == 'ubuntu-latest'

    - name: Set up Vcpkg
      run: git clone https://github.com/Microsoft/vcpkg.git
      run: ./vcpkg/bootstrap-vcpkg.sh

    - name: Install PcapPlusPlus with Vcpkg
      run: ./vcpkg/vcpkg install pcapplusplus

    - name: Build and Test PcapPlusPlus examples
      run: |
        cd Examples
        cmake -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -S . -B build
        cmake --build build
